name: Publish to NuGet

on:
  release:
    types: [published]
  workflow_dispatch:
    
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'
          
      - name: Get version from release
        id: get_version
        run: echo "##[set-output name=VERSION;]${{ github.event.release.tag_name }}"

      - name: Set version in .csproj
        run: |
          VERSION=${{ github.event.release.tag_name }}
          echo "VERSION=${VERSION#v}" >> $GITHUB_OUTPUT
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Pack the project
        run: |
          dotnet pack ./src/ILovePDF/iLovePDF.csproj \
            --configuration Release \
            --output ./dist \
            -p:PackageVersion=${{ steps.get_version.outputs.VERSION }}

      - name: Publish to NuGet
        run: |
          dotnet nuget push "./dist/*.nupkg" \
            --api-key ${{ secrets.NUGET_TOKEN }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
