name: Publish to NuGet

on:
  release:
    types: [published]
  workflow_dispatch:
    
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'
          
      - name: Get and Clean Version
        id: vars
        run: |
          RAW_VERSION=${{ github.event.release.tag_name }}
          CLEAN_VERSION=${RAW_VERSION#v}
          echo "VERSION=$CLEAN_VERSION" >> $GITHUB_OUTPUT
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Pack the project
        run: |
          dotnet pack ./src/ILovePDF/iLovePDF.csproj \
            --configuration Release \
            --output ./dist \
            -p:PackageVersion=${{ steps.vars.outputs.VERSION }}

      - name: Publish to NuGet
        run: |
          dotnet nuget push "./dist/*.nupkg" \
            --api-key ${{ secrets.NUGET_TOKEN }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
